export const BASE_URL                = 'https://app.kostzy.com/';
export const BASE_URL_UPLOAD         = BASE_URL+'/api/upload';
export const URL_UPLOAD              = BASE_URL+'/uploads';
export const OS_APPID                = '703e8137-13ea-4623-97d5-63f447ea4320';
export const OS_GOOGLEID             = '420369396589';

export const DEFAULT_REQUEST         = 'POST';
export const DEFAULT_TIMEOUT         = 60000;
export const DEFAULT_MAX_FILE_SIZE   = 8000000; // 8MB
export const DEFAULT_DIR_DOWNLOAD    = 'Koszy';
export const DEFAULT_DB_USER         = 'KoszyApp';
export const DEFAULT_DB_HOME         = 'home';
export const DEFAULT_DB_CONNECTION   = 'noConnetion';
export const DEFAULT_DB_EXPIRES      = (1000 * 3600 * 24);
export const DEFAULT_PAGE            = 0;
export const DEFAULT_PERPAGE         = 20;
export const TIMER                   = 60;
export const APP_VERSION             = '1.1';
export const LOGO                    = require('../theme/img/logo.png');
export const LOGO_HOME               = require('../theme/img/logo2.jpg');
